### ISSUE TITLE
How to restore the Jetson Nano SD-CARD Devkit to the previous state, and the previous SD card cannot be turned on.

### ISSUE THREAD

**Issue by sanpis** [balena-os/jetson-flash#111]
How to restore the Jetson Nano SD-CARD Devkit to the previous state, and the previous SD card cannot be turned on.

**Comment by floion** [comment]
Hi. Can you detail on what the problem is and what you want to achieve?
The description you provided does not describe what is the problem you are facing with https://github.com/balena-os/jetson-flash

**Comment by sanpis** [comment]
> Hi. Can you detail on what the problem is and what you want to achieve? The description you provided does not describe what is the problem you are facing with https://github.com/balena-os/jetson-flash

I installed opendatacam on Jetson with a new SD-CARD using this tool and it worked fine. But I switched back to the SD-CARD of the previous nvidia system and found that it could not be started. How can I do to restore the previous system？

**Comment by floion** [comment]
Does your jetson sd nano devkit have an eMMC?

**Comment by sanpis** [comment]
This is an official devkit, and without an eMMC.

**Comment by sanpis** [comment]
> Does your jetson sd nano devkit have an eMMC?


This is an official devkit, and without an eMMC.

**Comment by sanpis** [comment]
> Hi @sanpis,
> 
> > But I switched back to the SD-CARD of the previous nvidia system and found that it could not be started.
> 
> You mean that Nvidia Ubuntu cannot be started anymore if you plug in the SD-CARD with Nvidia Ubuntu, after you flashed balenaOS with jetson-flash?

Yes.

**Comment by acostach** [comment]
@sanpis i's not possible to load Nvidia Ubuntu with the BalenaOS u-boot, which has been written by jetson-flash to the QSPI Flash when the device was provisioned. If you want to re-use the old Ubuntu sd-card you need to re-flash the QSPI using NVidia SDK Manager. You can use a third SD-CARD for that to ensure the original Ubuntu sd-card is preserved intact.

**Comment by sanpis** [comment]
> @sanpis i's not possible to load Nvidia Ubuntu with the BalenaOS u-boot, which has been written by jetson-flash to the QSPI Flash when the device was provisioned. If you want to re-use the old Ubuntu sd-card you need to re-flash the QSPI using NVidia SDK Manager. You can use a third SD-CARD for that to ensure the original Ubuntu sd-card is preserved intact.

It is very likely that this is the reason. Can the recovery function be added later, so that it will be more convenient for everyone to use.
