### ISSUE TITLE
Error preparing images for AGX Orin

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [balena-os/jetson-flash#161]
Attempting to flash an AGX Orin using the docker method.

I prepared the docker image on an Ubuntu 22.04 host:
* Checked out `master` (which was v0.5.73, i.e. d3c88e4 at time of writing)
* Ran `./build.sh -m jetson-agx-orin-devkit` to make a docker image
* Launched the image with: `docker run --privileged -v /dev:/dev -v /dev/bus/usb:/dev/bus/usb -v /run/udev/control:/run/udev/control -v /sys:/sys -v ~/Downloads:/data/images -it jetson-flash-image`
* Inside the docker container ran: `./bin/cmd.js -f /data/images/balena-cloud-devkit-gimli-jetson-agx-orin-devkit-5.3.22-v16.3.15.img -m jetson-agx-orin-devkit`
  * Having previously downloaded that draft BalenaOS release on advice from Ross Porter for testing with L4T r36

After the initial license output, this failed with:
```
Accept the Tegra Software License Agreement above? Type yes/no:yes
Consistency check done for /tmp/30/Linux_for_Tegra
Saved in /tmp/30
Successfully generated hash
Checking resin cache
Cache image check done
Extracting partition resin-boot from /tmp/30/resin/img to /tmp/30/resin
Extracting partition resin-rootA from /tmp/30/resin/img to /tmp/30/resin
Extracting partition resin-rootB from /tmp/30/resin/img to /tmp/30/resin
Extracting partition resin-state from /tmp/30/resin/img to /tmp/30/resin
Extracting partition resin-data from /tmp/30/resin/img to /tmp/30/resin
Data partition size in bytes: 212860928
Successfully generated hash
/usr/src/app/jetson-flash/node_modules/balena-image-fs/node_modules/ext2fs/lib/libext2fs.js:1
#### snip spew of minified code, presumably libext2fs.jsError: Cannot copy 'flash_l4t_t234_nvme_rootfs_enc.xml' to a subdirectory of itself, 'flash_l4t_t234_nvme_rootfs_enc.xml'.
    at /usr/src/app/jetson-flash/node_modules/fs-extra/lib/copy/copy.js:210:21
    at FSReqCallback.oncomplete (node:fs:192:23)

Node.js v18.20.4
```

**Comment by acostach** [comment]
Hi @mgabeler-lee-6rs , can you please let me know if adding `-c /tmp/Linux_for_Tegra` to bin/cmd.js like [here](https://github.com/balena-os/jetson-flash/pull/162) solves the flashing problem?
