### ISSUE TITLE
Expected to work with a Jetpack 4.2.2 image?

### ISSUE THREAD

**Issue by mhodgson** [balena-os/jetson-flash#17]
Hi there, I tried to use this tool with a fresh TX2 image (Jetson 4.2/Warrior) generated off master of https://github.com/balena-os/balena-jetson.

The flashing over USB appeared to finish successfully, but the board was bricked (nothing on screen, no boot). 

Is this tool expected to work for this use case, or does it need to be updated to work with the latest version of Jetpack? Sorry, I'm just not familiar enough with the guts of this thing to debug it further myself.

Thanks!

**Comment by telphan** [comment]
@mhodgson Yes, I believe the latest OS image and the version of L4T that this tool flashes are incompatible now. There is an open PR here #18 which should work with an image cut from master.

**Comment by mhodgson** [comment]
Ah, I figured as much. Thanks for the response. Looking forward to the L4T 32.2 support!
