### ISSUE TITLE
jetson-nano-emmc -  Invalid MBR boot signature issue

### ISSUE THREAD

**Issue by dhgokul** [balena-os/jetson-flash#33]
Please find the below steps to replicate invalid MBR issue

Step1: Flashed jetson nano pack 4.4 using etcher tool and configure jetson nano and installed packages and source code

Step 2: Take backup of SD card using below cmd
dd if=/dev/sdb1 conv=sync,noerror bs=64K | gzip -c > /home/sample/backup_image.img.gz

Step 3: We tried to reboot jetson nano using recovery mode

reboot --force forced-recovery

Step 4: And run below cmd and got  Invalid MBR boot signature issue

root@sample:~/jetson-flash# ./bin/cmd.js -f /home/sample/Downloads/backup_image.img.gz -m  jetson-nano-emmc
Consistency check done for /tmp/14307/Linux_for_Tegra
Saved in /tmp/14307
Successfully generated hash
Checking resin cache
Cache image check done
(node:14307) UnhandledPromiseRejectionWarning: SyntaxError: Invalid MBR boot signature. Expected 0xAA55, but saw 0x3EF3
    at Function.MBR.detectFormat (/home/sample/jetson-flash/node_modules/mbr/lib/mbr.js:73:11)
    at Function.MBR.parse (/home/sample/jetson-flash/node_modules/mbr/lib/mbr.js:54:20)
    at new MBR (/home/sample/jetson-flash/node_modules/mbr/lib/mbr.js:12:16)
    at getPartitionsFromMBRBuf (/home/sample/jetson-flash/node_modules/partitioninfo/build/partitioninfo.js:49:11)
    at /home/sample/jetson-flash/node_modules/partitioninfo/build/partitioninfo.js:100:18
(node:14307) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14307) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Any help appreciated !

**Comment by acostach** [comment]
Hi, the error you see appears because the image should be extracted. Please unpack the image and try again.
