### ISSUE TITLE
Xavier AGX - cannot find device "canX"

### ISSUE THREAD

**Issue by kmilo7204** [balena-os/jetson-flash#34]
Hi Balena team, 

Find a full description of our issue here.

Our problem is CAN bus related. When we tried to bring up the CAN modules we are getting the following error:

![Can-error](https://user-images.githubusercontent.com/49252525/100128686-94943600-2e4e-11eb-84da-76acf7825fd2.png)

Before bringing it up we are performing the GPIO configuration to enable CAN (FInd more information [here](https://github.com/hmxf/can_xavier)). All is done without any error: however when we run:

```bash
ip link set can0 type can bitrate 500000
```

We got the message (Cannot find device "can0").

We have done the same process with three boards (Xavier AGX) without any major problem, but we do not understand why is it happening. We have tried a bunch of thing but none of them seems to work so far. Are we missing some critical step or is there any modification we can do to deal with this issue?

Find additional information about the flashing process here:
* AGX is plugged into the PC and is in recovery mode
* ./bin/cmd.js -f balena-cloud-Application-jetson-xavier-2.51.1+rev3-v11.4.10.img -m jetson-xavier (We tried with sudo as well)
* Once done we unplug and reboot the device.

Using your production image balenaOS 2.51.1+rev3 with supervisor version 11.4.10

Please let me know if any additional information is required.

**Comment by acostach** [comment]
@kmilo7204 I could not reproduce this issue with newer image releases. Please re-open this ticket if the issue still occurs with the latest release.
