### ISSUE TITLE
Cannot flash Jetson Xavier NX EMMC mounted at Nano devkit

### ISSUE THREAD

**Issue by ClintHaerinck** [balena-os/jetson-flash#45]
Command used: `./jetson-flash/bin/cmd.js -f ~/Downloads/Xaviernx/balena-cloud-<application>-jetson-xavier-nx-devkit-emmc-2.58.6+rev5-dev-v11.14.0.img -m jetson-xavier-nx-devkit-emmc -o /tmp/balena-cache-nx-32-4-3 -p`

jetson-flash revision checked out: v0.5.2

lsusb output: `Bus 001 Device 040: ID 0955:7e19 NVIDIA Corp.`

Output:
```
Consistency check done for /tmp/balena-cache-nx-32-4-3/jetson-flash-artifacts/resin
Using cached resin image
###############################################################################
# L4T BSP Information:
# R32 , REVISION: 4.3
###############################################################################
Error: probing the target board failed.
       Make sure the target board is connected through 
       USB port and is in recovery mode.
```

**Comment by hajmf** [comment]
Hi, I have the same issue: probing failed to start flash, using flash.sh. @ClintHaerinck  Did you find a solution?
