### ISSUE TITLE
Xavier flash and boot from SSD as opposed to EMMC

### ISSUE THREAD

**Issue by cpsamtec** [balena-os/jetson-flash#46]
Hi,

The built-in emmc is only 32GB. We would like to flash and boot from an attached NVMe SSD. I think the flash utility has an external parameter, however I do not believe it is exposed. An alternative would be to allow balena daemon to use the external drive to store images, however I do not think this is supported by balena.

**Comment by acostach** [comment]
Hi @cpsamtec, booting from other medium, any other than the eMMC in this case is not supported with jetson devices running BalenaOS. You may however mount any storage volume inside the container and store data there.

**Comment by acostach** [comment]
Closing as per the above.
