### ISSUE TITLE
dependency resin-image-fs is broken

### ISSUE THREAD

**Issue by aethernet** [balena-os/jetson-flash#67]
To be able to flash, I had to rebuild resin-image-fs/node-modules/ext2fs (after the initial npm install)

```
$ npm i -g node-gyp
$ cd node-modules/resin-image-fs/node-modules/ext2fs/
$ node-gyp rebuild
```

Don't know if it's an `resin-image-fs` version issue, will report it in that repository as well.

(context : ubuntu 18.04 live on a i5 Nuc with node 12)

link to the `resin-image-fs` issue : https://github.com/balena-io-modules/balena-image-fs/issues/58

**Comment by acostach** [comment]
Fixed by https://github.com/balena-os/jetson-flash/pull/106
