### ISSUE TITLE
r34.1 Release date

### ISSUE THREAD

**Issue by dHofmeister** [balena-os/jetson-flash#86]
Dear jetson-flash developers, 

Today jetpack 5.0 will be officially released. https://developer.nvidia.com/embedded/jetpack

I was wondering when the Xavier NX will be flashable with version r34.1?  

Greetings

**Comment by acostach** [comment]
Hi @dHofmeister , we do not have a timeline for updating Xavier NX to 34.1. See https://github.com/balena-os/balena-jetson/issues/317 

Once we have any updates, we will post them there.
