### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by etohana** [balena-os/jetson-flash#90]
jetson-xavier-nx-devkit-emmc, Board Family: t186ref, SoC: Tegra 194, 
balena-cloud-parking-lot-jetson-xavier-nx-devkit-emmc-2.99.27+rev1-v14.0.8.img
Node.js 12.22.12
Python 3.10.6
Pop!_OS 22.04 LTS

Greetings:
I am trying to flash BalenaOS on a Xavier NX Module (w/ eMMC). The procedure seems to proceed okay until this point:

> File "/tmp/Linux_for_Tegra/bootloader/tegraflash_internal.py", line 164, in print_process
>     outputchar = output.decode('ascii')
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
> Failed flashing t186ref.

Is 'ascii' the problem? Should it be 'utf-8' instead? Any advice on how to proceed would be appreciated.

**Comment by pipex** [comment]
Hi there, thanks for reporting this. I found this forum topic on Nvidia that seems to be related
https://forums.developer.nvidia.com/t/flashing-xavier-nx-emmc/187379

Could you make sure that you are using `python2` as your default python interpreter, i.e. that the binary for `python` points to `python2` and try again?

Please let us know if that works for you

**Comment by pipex** [comment]
Thank you for letting us know. I have created a PR updating the README instructions here #91
